version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: example
      POSTGRES_DB: kafka_example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081


    
