version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5439:5432"
    environment:
      POSTGRES_PASSWORD: depixen-pass
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081


    
